"""pokemon table added datetime 02

Revision ID: 4a6a4dcb43c8
Revises: 88368b1dcb48
Create Date: 2023-12-21 19:08:30.972507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4a6a4dcb43c8'
down_revision: Union[str, None] = '88368b1dcb48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pokemon', 'birth_date',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pokemon', 'birth_date',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
