"""Addition of category ID in pokemon table

Revision ID: 4e272b3aaaf9
Revises: 7e179a9fa1cf
Create Date: 2023-12-23 19:06:02.790083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e272b3aaaf9'
down_revision: Union[str, None] = '7e179a9fa1cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pokemon', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pokemon', type_='foreignkey')
    op.drop_column('pokemon', 'category_id')
    # ### end Alembic commands ###
