"""Name split in owner table

Revision ID: 69b0db8f62b0
Revises: e3ee0028494c
Create Date: 2023-12-24 09:31:42.160247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '69b0db8f62b0'
down_revision: Union[str, None] = 'e3ee0028494c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner', sa.Column('first_name', sa.String(length=150), nullable=True))
    op.add_column('owner', sa.Column('last_name', sa.String(length=150), nullable=True))
    op.drop_column('owner', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner', sa.Column('name', mysql.VARCHAR(length=150), nullable=True))
    op.drop_column('owner', 'last_name')
    op.drop_column('owner', 'first_name')
    # ### end Alembic commands ###
