"""Review Relationship with Rating

Revision ID: 6ea92fb9354e
Revises: 469a60625536
Create Date: 2023-12-24 01:00:15.560802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ea92fb9354e'
down_revision: Union[str, None] = '469a60625536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'rating')
    # ### end Alembic commands ###
