"""pokemon table added datetime

Revision ID: 88368b1dcb48
Revises: ff53c95265fa
Create Date: 2023-12-21 18:51:12.144638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88368b1dcb48'
down_revision: Union[str, None] = 'ff53c95265fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('birth_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon', 'birth_date')
    # ### end Alembic commands ###
