"""Review Relationship with Reviewer - 02

Revision ID: 94d9a7ab3885
Revises: c2922c3e8061
Create Date: 2023-12-24 01:26:32.059963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '94d9a7ab3885'
down_revision: Union[str, None] = 'c2922c3e8061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('reviewer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'review', 'reviewer', ['reviewer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('reviewer_ibfk_1', 'reviewer', type_='foreignkey')
    op.drop_column('reviewer', 'review_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviewer', sa.Column('review_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('reviewer_ibfk_1', 'reviewer', 'review', ['review_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'reviewer_id')
    # ### end Alembic commands ###
