"""Country Relationship in Owner Table

Revision ID: 9f50ef9923e7
Revises: 69b0db8f62b0
Create Date: 2023-12-24 09:39:20.092392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f50ef9923e7'
down_revision: Union[str, None] = '69b0db8f62b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner', sa.Column('country_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'owner', 'country', ['country_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'owner', type_='foreignkey')
    op.drop_column('owner', 'country_id')
    # ### end Alembic commands ###
