"""Review Relationship with Reviewer

Revision ID: c2922c3e8061
Revises: 6ea92fb9354e
Create Date: 2023-12-24 01:22:36.999426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2922c3e8061'
down_revision: Union[str, None] = '6ea92fb9354e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviewer', sa.Column('review_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reviewer', 'review', ['review_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviewer', type_='foreignkey')
    op.drop_column('reviewer', 'review_id')
    # ### end Alembic commands ###
