"""Addition of category ID in pokemon table - 02

Revision ID: dbea8c426d2c
Revises: 4e272b3aaaf9
Create Date: 2023-12-23 19:13:02.679009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dbea8c426d2c'
down_revision: Union[str, None] = '4e272b3aaaf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pokemon', 'category_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pokemon', 'category_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
