"""Added Owner in Pokemon Table

Revision ID: e3ee0028494c
Revises: 94d9a7ab3885
Create Date: 2023-12-24 09:28:46.410381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3ee0028494c'
down_revision: Union[str, None] = '94d9a7ab3885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pokemon', 'owner', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pokemon', type_='foreignkey')
    op.drop_column('pokemon', 'owner_id')
    # ### end Alembic commands ###
